# Generated by Django 2.1.3 on 2018-12-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181212_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user_profile',
        ),
    ]
